### ISSUE TITLE
Resort Page

### ISSUE THREAD

**Issue by kavitadrozario** [kkavion/ih-site#24]
1. Remove background.
2. To add Fact File in the place of your query. Just like POIS  page
3. Your query would appear as a button/popup which would be at the end  of the fact file.
4. The icons would be in the fact file.
5. Map to be incorporated below the fact file above Indulgence carousal just like POI Page

**Comment by kavitadrozario** [comment]
**Resort Page:**

1. **Room Subsection:**
a) Asterix to be made bold just like in event

2. **Offer, Event & Dayout subsection:** 
a) Space between Package name and descriptor to be added in the rows
b) Icons to be added just like offer subsection

3. Compare button text to be in one line.

4. Dining, Recreation & Wellness Internal tab:
a) Residential Package & Dayout Package - Space above just like in activities below it.

5. Wedding tab: 
a) Wedding Plans & Day Retreat Package - Space above just like in activities below it.

6. Conference Internal Tab:
a) Conference Plans & Day Retreat  Plans and Acitivities - Space above just like above activities in Wedding Internal tab.

7. Terms Internal tab:
a) Spacing below the Headings - Reduce it to half

8. Direction: Remove Map

10. Events Internal Tab:
a) Give subheadings like in Resort Tab Jan - March, Apr - June, July - Sept, Oct - Dec

Important Links - Remove Banquets and Lawns

**Comment by ericpremraju** [comment]
> * Space between Package name and descriptor to be added in the rows
> 
> *

To be decided
