### ISSUE TITLE
Resort Page amendments

### ISSUE THREAD

**Issue by kavitadrozario** [kkavion/ih-site#26]
- [x] Your Query - Pop-up  to be exactly like before in appearance i.e narrow
- [x] Icon - size to be same as destination page
- [ ] Package - Room Subsection - The row to be gray from Package Inclusions just like offer subsection. 
- [x] Package - Room Subsection - The asterik has to be like in the offer subsection.
- [x] Offer, Event & Day-Out Subsection - As suggested interchange descriptor and icons in the rows
- [x] Important Links - Space above it to be same as per the previous subheadings (activities)
- [ ] Terms (Internal Tab) - Give appropriate space above "Arrival and Departure"
- [x] Events (Internal Tab) - Provide space between the ads
- [x] Events (Internal Tab) - Reduce space below the headings

**Comment by ericpremraju** [comment]
> * Package - Room Subsection - The row to be gray from Package Inclusions just like offer subsection.
They are not the same objects, they'll look bad
> * Terms (Internal Tab) - Give appropriate space above "Arrival and Departure"
This is not required
